before_install:
  - php /home/travis/.phpenv/versions/5.5/bin/composer self-update
  - composer install
install:
  - composer self-update
  - composer update --prefer-dist
  - /home/travis/.phpenv/versions/5.5/bin/composer self-update

language: php
php:
  - 5.5
  - 5.4
  - hhvm
script: phpunit Test.php

